HonlineCoreMVC/Controllers/AgentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Bl;
using HonlineCoreMVC.Common.DTO;
using HonlineCoreMVC.Common.Utility;
using HonlineCoreMVC.Helper;
using HonlineCoreMVC.Models.AccountViewModels;
using HonlineCoreMVC.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace HonlineCoreMVC.Controllers
{
    [Authorize(Roles = Consts.AdminUser)]
    public class AgentController : Controller
    {
        public AgentController()
        {
            _customerLogic = new CustomerLogic();
            _loanPaymentsCalculator = new LoanPaymentsCalculator();
            _customerDetailsHelper = new CustomerDetailsHelper();
        }

        private readonly CustomerLogic _customerLogic;
        private readonly LoanPaymentsCalculator _loanPaymentsCalculator;
        private readonly CustomerDetailsHelper _customerDetailsHelper;

        //Get Agent/Index
        public IActionResult Index()
        {
            var users = _customerLogic.GetApplicationUsers();

            var UsersDTO = new List<UserDTO>();

            foreach (var user in users)
            {
                UsersDTO.Add
                    (new UserDTO
                    {
                        Id = user.Id,
                        FirstName = user.FirstName,
                        LastName = user.LastName,
                        Email = user.Email,
                    });
            }
            return View(UsersDTO);
        }
        //Get Agent/GetCustomerDetails
        [HttpGet]
        public IActionResult GetCustomerDetails(string userId)
        {        
            var viewModel = _customerDetailsHelper.GetCustomerDetailsViewModel(userId.Trim());
            return PartialView("_CustomerDetails", viewModel);
        }
    }
}

HonlineCoreMVC/Controllers/CustomerDetailsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Bl;
using HonlineCoreMVC.Common.Utility;
using HonlineCoreMVC.Helper;
using HonlineCoreMVC.Models.AccountViewModels;
using HonlineCoreMVC.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace HonlineCoreMVC.Controllers
{
    [Authorize(Roles = Consts.AdminUser + "," + Consts.CustomerEndUser)]
    public class CustomerDetailsController : Controller
    {
        public CustomerDetailsController()
        {
            _customerLogicBl = new CustomerLogic();
            _loanPaymentsCalculator = new LoanPaymentsCalculator();
            _customerDetailsHelper = new CustomerDetailsHelper();
        }

        private readonly CustomerLogic _customerLogicBl;
        private readonly LoanPaymentsCalculator _loanPaymentsCalculator;
        private readonly CustomerDetailsHelper _customerDetailsHelper;


        //Get CustomerDetails/Index
        public async Task<IActionResult> Index(string userId)
        {
            if (string.IsNullOrWhiteSpace(userId))
            {
                userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
            }
            var customerDetailsViewModel = _customerDetailsHelper.GetCustomerDetailsViewModel(userId.Trim());
            return View(customerDetailsViewModel);
        }
    }
}

HonlineCoreMVC/Views/Shared/_CustomerDetails.cshtml
@model HonlineCoreMVC.ViewModel.CustomerDetailsViewModel

<br />
<h2>Customer Details</h2>
<hr />
<div class="row" style="padding-bottom:80px;">
    <div class="col-sm-6">
        <div class="row">
            <div class="col-sm-4">
                <label asp-for="User.FirstName" class="control-label"></label>
            </div>
            <div class="col-sm-8" style="padding-bottom:5px;">
                <input asp-for="User.FirstName" disabled class="form-control" />
            </div>
        </div>
        <div class="row">
            <div class="col-sm-4">
                <label asp-for="User.LastName" class="control-label"></label>
            </div>
            <div class="col-sm-8" style="padding-bottom:5px;">
                <input asp-for="User.LastName" disabled class="form-control" />
            </div>
        </div>
        <div class="row">
            <div class="col-sm-4">
                <label asp-for="User.Taz" class="control-label"></label>
            </div>
            <div class="col-sm-8" style="padding-bottom:5px;">
                <input asp-for="User.Taz" disabled class="form-control" />
            </div>
        </div>
        <div class="row">
            <div class="col-sm-4">
                <label asp-for="User.BirthDate" class="control-label"></label>
            </div>
            <div class="col-sm-8" style="padding-bottom:5px;">
                <input asp-for="User.BirthDate" type="date" disabled class="form-control" />
            </div>
        </div>
        <div class="row">
            <div class="col-sm-4">
                <label asp-for="User.LoanAmount" class="control-label"></label>
            </div>
            <div class="col-sm-8" style="padding-bottom:5px;">
                <input asp-for="User.LoanAmount" disabled class="form-control" />
            </div>
        </div>
        <div class="row">
            <div class="col-sm-4">
                <label asp-for="User.PeriodInMonths" class="control-label"></label>
            </div>
            <div class="col-sm-8" style="padding-bottom:5px;">
                <input asp-for="User.PeriodInMonths" disabled class="form-control" />
            </div>
        </div>
    </div>
</div>


@if (!Model.LoanPayments.Any())
{
    <div class="text-danger">Loan payments not found !!!</div>
}
else
{
    <div class="form-border">
        <table class="table table-condensed table-hover">
            <tr>
                <th>
                    @Html.DisplayNameFor(m => m.LoanPayments.FirstOrDefault().Index)
                </th>
                <th>
                    @Html.DisplayNameFor(m => m.LoanPayments.FirstOrDefault().Balance)
                </th>
                <th>
                    @Html.DisplayNameFor(m => m.LoanPayments.FirstOrDefault().MonthyPayment)
                </th>
                <th>
                    @Html.DisplayNameFor(m => m.LoanPayments.FirstOrDefault().InterestForMonth)
                </th>
                <th>
                    @Html.DisplayNameFor(m => m.LoanPayments.FirstOrDefault().PrincipalForMonth)
                </th>
            </tr>
            @foreach (var loanPayment in Model.LoanPayments)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(l => loanPayment.Index)
                    </td>
                    <td>
                        @if (loanPayment.Balance != 0)
                        {
                            @Html.DisplayFor(l => loanPayment.Balance)
                        }
                    </td>
                    <td>
                        @if (loanPayment.MonthyPayment != 0)
                        {
                            @Html.DisplayFor(l => loanPayment.MonthyPayment)
                        }
                    </td>
                    <td>
                        @if (loanPayment.InterestForMonth != 0)
                        {
                            @Html.DisplayFor(l => loanPayment.InterestForMonth)
                        }
                    </td>
                    <td>
                        @if (loanPayment.PrincipalForMonth != 0)
                        {
                            @Html.DisplayFor(l => loanPayment.PrincipalForMonth)
                        }
                    </td>
                </tr>
            }
        </table>
    </div>
}

HonlineCoreMVC/Views/Shared/_Layout.cshtml
@using HonlineCoreMVC.Common.Utility
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HonlineCoreMVC</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">HonlineCoreMVC</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    @if (User.IsInRole(Consts.AdminUser))
                    {
                        <li><a asp-area="" asp-controller="Agent" asp-action="Index">Agent back office</a></li>
                    }
                    @if (User.IsInRole(Consts.AdminUser) || User.IsInRole(Consts.CustomerEndUser))
                    {
                        <li><a asp-area="" asp-controller="CustomerDetails" asp-action="Index">Customer Details</a></li>
                    }
                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - HonlineCoreMVC</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

HonlineCoreMVC/Views/Shared/_Test.cshtml
<div>hello world</div>